spring:
  application:
    name: transazionePos
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  server:
    port: 8080
  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36}.%M() : %m%n)"
